### ISSUE TITLE
Use a MineConnect Server on another ip

### ISSUE THREAD

**Issue by Guillaume1868** [ichbinbenni/MineConnectAppPublic#1]
Hello,

I want to use mineconnect with my minecraft server hosted on a pterodactyl panel (aka on a docker without shell access). Would it be possible to support the use of a server on another ip ?

**Comment by ichbinbenni** [comment]
Hey, currently it isn't possible because both parts (Server and Plugin) need to access an SQLite database.
I'll add it to the feature request list.

**Comment by Guillaume1868** [comment]
Thanks !

**Comment by Guillaume1868** [comment]
I have 2 suggestions :

*	Use an mysql database
*	I don’t know if possible, but a version with a server that runs with the plugin jar

**Comment by ichbinbenni** [comment]
A SQL server is relatively hard to set up and you need to install it to your pc/server. But MineConnect should also be available for smaller groups and servers, where not everyone has an SQL database. So this isn't an option.
To make a kind of portable plugin-only version could be a solution. Thanks for your feedback :)

**Comment by ichbinbenni** [comment]
@Guillaume1868 Hey. We released a new version where you don't need terminal access anymore. It is just the plugin file you have to add to your plugin folder.
You can download it from the [website](https://mineconnect.ibb-games.de/versions.html).

I hope this will solve your problem and you can try MineConnect.

**Comment by Guillaume1868** [comment]
Thanks :),

Will try it next time i make a server.
