### ISSUE TITLE
Use of Domain Name

### ISSUE THREAD

**Issue by boydspace** [ichbinbenni/MineConnectAppPublic#2]
I am trying to use a domain name for the server instead of the IP. I have my domain name running through CloudFlare and have a DNS SRV record setup for both ports necessary. I am having the difficulty that the server is not working/responding when I input the domain name instead of the IP address.

Any help would be appreciated!

**Comment by ichbinbenni** [comment]
Hey, it's hard to tell without more information. May it possible that you share your DNS configuration?

**Comment by boydspace** [comment]
![image](https://user-images.githubusercontent.com/11556839/80495075-70fb2280-8935-11ea-8b86-9acfd5a2feea.png)
![image](https://user-images.githubusercontent.com/11556839/80495087-748ea980-8935-11ea-8417-2754c60f7f64.png)

Sorry it’s as screen shots. I’m away from my computer for the moment and this was the easiest way for me to do it.

**Comment by ichbinbenni** [comment]
For me it looks fine, so honestly I don't know. Sorry.

**Comment by ichbinbenni** [comment]
This issue isn't directly related to MineConnect. So I close this issue. If you found a solution or need further support feel free to reopen it.

**Comment by ichbinbenni** [comment]
@boydspace Hey. We released a new version. It is easier to setup. Maybe you can give it a second try :).
