### ISSUE TITLE
An internal error occured - performing /registerMe

### ISSUE THREAD

**Issue by RepuTrX** [ichbinbenni/MineConnectAppPublic#4]
Hi,

I pulled the plugin into my plugins folder.
I'm running Bukkit 1.16.4 with no other plugins.

The server starts without any error messages. I opped myself and tried to enter /registerMe.
I get the folowing message:

An internal error occured while attempting to perform this command

Any idea why?

Btw: very nice idea for a plugin.

**Comment by RepuTrX** [comment]
After switching from the bukkit.jar to the spigot, everything works fine.

**Comment by ichbinbenni** [comment]
Thanks for your feedback.
I will look into the problem to support CraftBukkit after the Christmas holidays. 🎄
