### ISSUE TITLE
Can’t connect/ connection time out

### ISSUE THREAD

**Issue by NotLopX** [ichbinbenni/MineConnectAppPublic#7]
Every time I try to connect using port 4711, I get timed out. Do I need to port forward this port? Or am I doing something wrong, everything is installed the plug-in, set the port and register for the code

**Comment by ichbinbenni** [comment]
Was fixed in an email discussion. 
If someone runs into the same error look [here](https://github.com/ichbinbenni/MineConnectAppPublic/blob/master/help.md)
